### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by lurebgi** [screamer/miteFinder#1]
Hi,

Could you please provide more info on how to install and run? After compiling it, I had miteFinderTest. However, miteFinderTest seems to be running forever without producing any results. 

below is the code I used
`/scratch/luohao/software/miteFinder/miteFinderTest -input bb.fa -threshold 0.5 -output bb`

Thanks!

**Comment by jhu99** [comment]
Hello，

Thanks for your email. You forgot a profile which is necessary for the running. Please see the example in the run.sh. 

Best,
Jialu 

发自我的 iPhone

**Comment by lurebgi** [comment]
Thanks, now it works.
