### ISSUE TITLE
Issues in program

### ISSUE THREAD

**Issue by Max-hub1** [screamer/miteFinder#10]
Dear Jialu Hu,

Thank you for your great software!
In your paper you mentioned that you clustered the mite candidates into families. However, I did not find the 
code for clustering in your program. Could you give me more details about the clustering procedure?

Best regards,
Max

**Comment by 13207437722** [comment]
In our tool, miteFinderII, the clustering of MITE candidate sequences isn't directly included. Clustering is a subsequent analysis step. We compare the similarities between various MITE sequences using BLASTn and then use this similarity information to run clustering algorithms in a network analysis tool (like Cytoscape), grouping similar MITE sequences into different families

-- a student from professor hu
