### ISSUE TITLE
Errorneous MITEFinderII output

### ISSUE THREAD

**Issue by dipsaha** [screamer/miteFinder#3]
I am trying to identify MITE in a published genome sequence using MITEFinder II in Ubuntu14.04 LTS OP system. The following script was used:

./miteFinder -input my/fast/file.fa -output my/mitefinder/out -pattern_scoring ./profile/pattern_scoring.txt -threshold 0.5

The program ran smoothly to produce a fasta seq output of probable MITEs. However, the file consisted of some invalid characters.

![image](https://user-images.githubusercontent.com/31880276/52939498-5967f780-338a-11e9-9f5b-54fb5549937a.png)

Please advise to sort the above problem.

Moreover, it will be good if you can throw some light on (i) explaining the header line of the output fasta sequences; (ii) Possible methods to identify TSD and TIR sequences; (iii) How to classify MITEs based on family; and (iv) tool for design primers from MITE-flanking sequence.

Thanks
Dip

**Comment by nwpuzhengyan** [comment]
Thank you for your advise, could you please provide me the input data of you? I want to find the problem by the data

**Comment by dipsaha** [comment]
Please find below attached a part of the input file as desired by you. Please also let me know about the description of the header line in the output and how to annotate (i) TIR; (ii) TSD; and (iii) MITE classification from the output file. Let me know if you can access the attached file.

[sample.fasta.tar.gz](https://github.com/screamer/miteFinder/files/2879406/sample.fasta.tar.gz)

Thanks

**Comment by nwpuzhengyan** [comment]
Thank you for your advise. I had modified the program and you can run it again. The description of the header line is just like this.
>mite|28|586|595|816|825|t3|591|m1|ave_score:0.611172
The 28 means the serial number of chromosome and 586,595,816,825 is the position of TIR. t3 means the length of TSD is 3. The program does not contain the classification of mite, so we run cluster analysis in output file by blastn. If you have any other questions, please contact me by email-yan.zheng@nwpu-bioinformatics.com. Thank you again.

**Comment by dipsaha** [comment]
Thanks, the program now worked. But again, I would be glad if scripts are made/posted to extract the TIR and TSD sequences in a batch or at least find them in the header of the output MITE sequences and classify the MITEs based on homology. 

Regards
Dip
