### ISSUE TITLE
how to parse the output result

### ISSUE THREAD

**Issue by huangziyan11111** [screamer/miteFinder#4]
Hi,
Through I see the readme, I counld not know which the exact position of MITE, and the header is like this: mite|1|170025|170037|170078|170090|t2|170026|m1|ave_score:0.711664, how can I get the MITE position?
I waiting for your reply, thank you.

**Comment by nwpuzhengyan** [comment]
The description of the header line is just like this：
mite|28|586|595|816|825|t3|591|m1|ave_score:0.611172
The 28 means the serial number of chromosome and 586,595,816,825 is the position of TIR. t3 means the length of TSD is 3. If you have any other questions, please contact me by email-yan.zheng@nwpu-bioinformatics.com. Thank you.

**Comment by aubombarely** [comment]
Hello, 

  First of all, nice tool.

  In the example that you mention. What 591 and m1 means? Is the 591 the position of the TSD? Would be possible to get the TSD sequence in the header? Also could you add this description to the README file? Thank so much.

  Best regards

  Aureliano

**Comment by nwpuzhengyan** [comment]
Thank you for your question, t3 means the length of TSD is 3 and m1 means the TIR is an imperfect inverted repeats. The 591 is the position of  mismatch base. If you have any other questions, please contact me by email-yan.zheng@nwpu-bioinformatics.com. Thank you again.

**Comment by nwpuzhengyan** [comment]
Respected  Professor Sung:

Thank you for your question.  t3 means the length of TSD is 3 and m1 means the TIR is an imperfect inverted repeats. 
The 591 is the position of mismatch base.The  imperfect inverted repeats is just like the below graph. The 591 is the position 
of mismatch base.
 


Sincerely
Yan Zheng 
Northwestern Polytechnical University

------------------------------------------------------------------
发件人：Aureliano Bombarely <notifications@github.com>
发送时间：2019年3月20日(星期三) 20:26
收件人：screamer/miteFinder <miteFinder@noreply.github.com>
抄　送：Yan Zheng <yan.zheng@nwpu-bioinformatics.com>; Comment <comment@noreply.github.com>
主　题：Re: [screamer/miteFinder] how to parse the output result (#4)

Hello,
First of all, nice tool.
In the example that you mention. What 591 and m1 means? Is the 591 the position of the TSD? Would be possible to get the TSD sequence in the header? Also could you add this description to the README file? Thank so much.
Best regards
Aureliano

**Comment by nwpuzhengyan** [comment]
Respected  Aureliano:

I am sorry to call your wrong name in previous email. Thank you for your question.  t3 means the length of TSD is 3 and m1 means the TIR is
an imperfect inverted repeats. The 591 is the position of mismatch base.The  imperfect inverted repeats is just like the below graph.
The 591 is the position of red base. If you have other questions, you can ask me without hesitation.
 

Sincerely
Yan Zheng 
Northwestern Polytechnical University

------------------------------------------------------------------
发件人：Aureliano Bombarely <notifications@github.com>
发送时间：2019年3月20日(星期三) 20:26
收件人：screamer/miteFinder <miteFinder@noreply.github.com>
抄　送：Yan Zheng <yan.zheng@nwpu-bioinformatics.com>; Comment <comment@noreply.github.com>
主　题：Re: [screamer/miteFinder] how to parse the output result (#4)

Hello,
First of all, nice tool.
In the example that you mention. What 591 and m1 means? Is the 591 the position of the TSD? Would be possible to get the TSD sequence in the header? Also could you add this description to the README file? Thank so much.
Best regards
Aureliano

**Comment by aubombarely** [comment]
Thank you. I am using your tool for genome annotation. 
Would be possible to get an extra function to get a GFF file with the annotation specifying where the TSD and the TID regions are?
Best regards
Aureliano

**Comment by nwpuzhengyan** [comment]
Yeah, it is easy to change the function of output. Do you mean to change the result just like this way?
mite|28|586|595|816|825|t3|591|m1|ave_score:0.611172
changed to 
chr28 MiteFinder Mite 586 825 ave_score:0.611172 + . TSD=583,585,826,828
