### ISSUE TITLE
How to keep the actual chromosome name in the output?

### ISSUE THREAD

**Issue by bioteksampath** [screamer/miteFinder#6]
Hi,
Thanks for this good tool.
I was wondering, how do you keep the original chromosome name in output fasta header?
miteFInder renames chromosomes to 1,2,3... But it is confusing when we want to do some downstream analysis 
do you have any suggestions?
Thanks

for example 
`>mite|1|17871177|17871187|17871261|17871271|t4|17871184|m1|ave_score:0.849149
ATTGTTGTTTGGATTGTTGTTTAAGTTTTTTTTTGGAATTATTTTGTGTTTTTGTTAAAA
TTCAAAACGTTTTCCTGTTTTTAAAACGTTTTTTGATTTTTAAAAACGTTTTTCAAGTTT
CCAATAATAAACTATGTATAATAAAACGTTTTTAAAAAATTTTAAAAATATTTAACAACA
TTTTTCTATAATTATAAAAATTTATAATTTTGTAT
>mite|1|19986949|19986959|19987279|19987289|t3|19986953|m1|ave_score:0.707483
ACAAAAAAGTGAAACATAAAATATTTCTAAAAGACTAATTTCTTTTTGATGATATTGATA
CTCATGAATATATTTGATATAAATAATAAAGAAGTGTACGAAAAAAACATAAAAAAAAAA`

expected fasta header

>mite|**Bna.chrA1**|17871177|17871187|17871261|17871271|t4|17871184|m1|ave_score:0.849149
>mite|**Bna.chrA2**|17871177|17871187|17871261|17871271|t4|17871184|m1|ave_score:0.849149

**Comment by jhu99** [comment]
Hello,



If you can do some coding, please rewrite these two lines as bellows and replace "chr" as its new name.

https://github.com/jhu99/miteFinder/blob/master/lib/mite_finder.h#:~:text=output%20%3C%3C%20%22,%3C%3Cstd%3A%3Aendl%3B

​

Best,

Jialu Hu
