### ISSUE TITLE
About pattern_scoring.txt

### ISSUE THREAD

**Issue by luisafmc** [screamer/miteFinder#9]
Hello

Thank you so much for developing this software. 

I am trying to run the inicial command, however, I will like to know more about the pattern_scoring.txt

What is this file and can we used for any sample?

Sincerely,
Loi

**Comment by 13207437722** [comment]
The pattern_scoring.txt file contains predefined patterns and their corresponding scores, helpingsoftware identify potential MITE sequences more accurately.Each pattern in the file is assigned a score based on its frequency in known MITE sequences and its biological relevance. These scores guide the software in distinguishing true MITE sequences from false positives.
you could read about “Filtration of candidates with low score” about the details
![image](https://github.com/jhu99/miteFinder/assets/74805990/91bf4183-a4c8-4419-a848-68121e37dafe)
As for whether this file can be used for any sample, theoretically, it can be used, but some adjustments may be needed based on your specific sample. If your sample comes from a different species or has different genomic characteristics than our original dataset, it may be necessary to update the scores in the pattern_scoring.txt file to better reflect the characteristics of your sample.

--a student from professor Hu
